### ISSUE TITLE
Player bullets collide with enemy bullets. :(

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/evade2-ldk-game#12]
Should only collide with enemies and asteroids.

**Comment by mschwartz** [comment]
It’s by design.  Shooting enemy bullets is good strategy sometimes.

**Comment by jaygarcia** [comment]
But the enemy bullets don't die. :(

**Comment by mschwartz** [comment]
The red ones seem hard to hit, but the green ones die easy.

I tried tweaking the collision sphere, but that made it too easy to kill the green ones.  THe sphere has radius of 64, the enemies are 128 wide/tall, so it’s a perfect number.

**Comment by mschwartz** [comment]
Go ahead and remove the check.


https://github.com/ModusCreateOrg/evade2-ldk-game/blob/master/Evade2/src/GameState/GPlayerBulletProcess.cpp#L69

**Comment by mschwartz** [comment]
I checked both arduboy and odroid sources and we do not hit bullets with bullets.

That said, in every game I ever played in the 80s, bullets do kill bullets.

**Comment by jaygarcia** [comment]
Resolved :)
